# Generated by Django 5.2.8 on 2025-11-16 18:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('contrasena', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('imagen_url', models.URLField()),
                ('año_fundada', models.PositiveSmallIntegerField()),
                ('fundador', models.CharField(max_length=100, unique=True)),
                ('pais_origen', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado_pedido', models.CharField(choices=[('P', 'Pendiente'), ('PR', 'En proceso'), ('E', 'Enviado'), ('C', 'Completado')], default='P', max_length=2)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('TC', 'Tarjeta de Crédito'), ('TD', 'Tarjeta de Debito'), ('PP', 'Paypal'), ('AP', 'Apple Pay'), ('GP', 'Google Pay')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('stock', models.PositiveIntegerField()),
                ('disponibilidad', models.CharField(choices=[('D', 'Disponible'), ('A', 'Agotado')], default='D', max_length=1)),
                ('departamento', models.CharField(choices=[('M', 'Mujeres'), ('H', 'Hombres'), ('U', 'Unisex'), ('J', 'Jovenes'), ('I', 'Infantil')], max_length=1)),
                ('categoria', models.CharField(choices=[('CQ', 'Chaquetas'), ('ZP', 'Zapatos'), ('PF', 'Perfumes'), ('SW', 'Sweaters'), ('CM', 'Camisas'), ('PN', 'Pantalones'), ('VS', 'Vestidos'), ('JR', 'Joyeria')], max_length=2)),
                ('imagen_url', models.URLField()),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='app_CasePoint.marca')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_CasePoint.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_CasePoint.producto')),
            ],
            options={
                'unique_together': {('producto', 'pedido')},
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(through='app_CasePoint.ProductoPedido', to='app_CasePoint.producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app_CasePoint.usuario'),
        ),
    ]
