# Generated by Django 5.2.7 on 2025-11-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_CasePoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('CQ', 'Chaquetas'), ('ZP', 'Zapatos'), ('PF', 'Perfumes'), ('SW', 'Sweaters'), ('CM', 'Camisas'), ('PN', 'Pantalones'), ('VS', 'Vestidos'), ('JR', 'Joyeria'), ('BA', 'Bolsos y Accesorios')], max_length=2),
        ),
    ]
