# Generated by Django 5.2.8 on 2025-11-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_CasePoint', '0002_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(choices=[('ADM', 'Administrador')], max_length=3),
        ),
    ]
